[package]
name = "textmation"
version = "0.1.0"
authors = ["Christian Vallentin"]
edition = "2018"

[[bin]]
name = "textmation"
path = "src/bin.rs"

[dependencies]
image = "0.21.1"
gif = "0.10.1"
rusttype = "0.7.6"

[dependencies.cpython]
version = "0.2"
features = ["extension-module"]
